apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: workloads-infra-kargo
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: workloads-infra
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: pre-prod
  namespace: workloads-infra-kargo
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: workloads-infra
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eu
  namespace: workloads-infra-kargo
  annotations:
    kargo.akuity.io/color: purple
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: workloads-infra
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-us
  namespace: workloads-infra-kargo
  annotations:
    kargo.akuity.io/color: orange
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: workloads-infra
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
