apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: workloads-infra
  namespace: workloads-infra-kargo
spec:
  subscriptions:
  - git:
      repoURL: GIT_CLUSTER_MGMT_URLGIT_ORG_NAME/eks-cluster-mgmt.git
      # insecureSkipTLSVerify: true
      branch: main
      includePaths:
      - workloads-infra/apps
