apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    example: ref-implementation
spec:
  destination:
    namespace: argo
    server: "https://kubernetes.default.svc"
  source:
    repoURL: https://GIT_CLUSTER_MGMT_URLGIT_ORG_NAME/eks-cluster-mgmt.git
    targetRevision: HEAD
    path: "./infra/argo-workflows/manifests/dev"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
