apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  labels:
    example: ref-implementation
spec:
  destination:
    namespace: backstage
    server: "https://kubernetes.default.svc"
  source:
    repoURL: GIT_CLUSTER_MGMT_URLGIT_ORG_NAME/eks-cluster-mgmt.git
    targetRevision: HEAD
    path: "./infra/backstage/manifests"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
