apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.12.1
      helm:
        releaseName: ingress-nginx
        values: |
          controller:
            service:
              type: LoadBalancer
              annotations:
                service.beta.kubernetes.io/aws-load-balancer-name: "hub-ingress"
                service.beta.kubernetes.io/aws-load-balancer-type: "external"
                service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
                service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
              loadbalancerClass: "service.k8s.aws/nlb"
              ports:
                http: 80
                https: 443
            containerPort:
              http: 80
              https: 443
          tcp:
            22: "gitlab/gitlab:22"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
