apiVersion: kro.run/v1alpha1
kind: EksclusterWithVpc
metadata:
  name: workload1
spec:
    name: workload1
    region: AWS_REGION
    k8sVersion: '1.30'
    accountId: '111222333444'
    nodesCount: 3
    cidr:
      vpcCidr: "10.0.0.0/16"
      publicSubnet1Cidr: "10.0.1.0/24"
      publicSubnet2Cidr: "10.0.2.0/24"
      privateSubnet1Cidr: "10.0.11.0/24"
      privateSubnet2Cidr: "10.0.12.0/24"
