apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: iamcontroller.kro.run
spec:
  schema:
    apiVersion: v1alpha1
    kind: IAMController
    spec:
      name: string | default=iam-controller
      namespace: string | default=default
      values:
        aws:
          region: string | default=us-west-2
        deployment:
          containerPort: integer | default=8080
          replicas: integer | default=1
        image:
          deletePolicy: string | default=delete
          repository: string | default=public.ecr.aws/aws-controllers-k8s/iam-controller
          tag: string | default=1.3.13
          resources:
            requests:
              memory: string | default=64Mi
              cpu: string | default=50m
            limits:
              memory: string | default=128Mi
              cpu: string | default=100m
        log:
          enabled: boolean | default=false
          level: string | default=info
        serviceAccount:
          name: string | default=ack-iam-controller-sa
          roleArn: string | required=true
  resources:
  - name: iamCRDGroup
    template:
      apiVersion: kro.run/v1alpha1
      kind: IAMCRDGroup
      metadata:
        name: ${schema.spec.name}-crd-group
      spec:
        name: ${schema.spec.name}-crd-group
  - name: serviceAccount
    template:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: ${schema.spec.values.serviceAccount.name}
        namespace: ${schema.spec.namespace}
        annotations:
          eks.amazonaws.com/role-arn: ${schema.spec.values.serviceAccount.roleArn}
  - name: deployment
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ${schema.spec.name}-deployment
        namespace: ${schema.spec.namespace}
        labels:
          app.kubernetes.io.name: ${schema.spec.name}-deployment
          app.kubernetes.io.instance: ${schema.spec.name}
      spec:
        replicas: ${schema.spec.values.deployment.replicas}
        selector:
          matchLabels:
            app.kubernetes.io.name: ${schema.spec.name}-deployment
            app.kubernetes.io.instance: ${schema.spec.name}
        template:
          metadata:
            labels:
              app.kubernetes.io.name: ${schema.spec.name}-deployment
              app.kubernetes.io.instance: ${schema.spec.name}
          spec:
            serviceAccountName: ${serviceAccount.metadata.name}
            containers:
            - command:
              - ./bin/controller
              args:
              - --aws-region
              - ${schema.spec.values.aws.region}
              - --enable-development-logging=${schema.spec.values.log.enabled}
              - --log-level
              - ${schema.spec.values.log.level}
              - --deletion-policy
              - ${schema.spec.values.image.deletePolicy}
              - --watch-namespace
              - ${schema.spec.namespace}
              image: ${schema.spec.values.image.repository}:${schema.spec.values.image.tag}
              name: controller
              ports:
                - name: http
                  containerPort: ${schema.spec.values.deployment.containerPort}
              resources:
                requests:
                  memory: ${schema.spec.values.image.resources.requests.memory}
                  cpu: ${schema.spec.values.image.resources.requests.cpu}
                limits:
                    memory: ${schema.spec.values.image.resources.limits.memory}
                    cpu: ${schema.spec.values.image.resources.limits.cpu}
              env:
              - name: ACK_SYSTEM_NAMESPACE
                value: ${schema.spec.namespace}
              - name: AWS_REGION
                value: ${schema.spec.values.aws.region}
              - name: DELETE_POLICY
                value: ${schema.spec.values.image.deletePolicy}
              - name: ACK_LOG_LEVEL
                value: ${schema.spec.values.log.level}              
              ports:
              - containerPort: 80
  - name: clusterRoleBinding
    template:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: ${schema.spec.name}-clusterrolebinding
      roleRef:
        kind: ClusterRole
        apiGroup: rbac.authorization.k8s.io
        name: ${clusterRole.metadata.name}
      subjects:
      - kind: ServiceAccount
        name: ${serviceAccount.metadata.name}
        namespace: ${serviceAccount.metadata.namespace}
  - name: clusterRole
    template:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: ${schema.spec.name}-clusterrole
      rules:
      - apiGroups:
        - ""
        resources:
        - configmaps
        verbs:
        - get
        - list
        - patch
        - watch
      - apiGroups:
        - ""
        resources:
        - namespaces
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - ""
        resources:
        - secrets
        verbs:
        - get
        - list
        - patch
        - watch
      - apiGroups:
        - iam.services.k8s.aws
        resources:
        - groups
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - iam.services.k8s.aws
        resources:
        - groups/status
        verbs:
        - get
        - patch
        - update
      - apiGroups:
        - iam.services.k8s.aws
        resources:
        - instanceprofiles
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - iam.services.k8s.aws
        resources:
        - instanceprofiles/status
        verbs:
        - get
        - patch
        - update
      - apiGroups:
        - iam.services.k8s.aws
        resources:
        - openidconnectproviders
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - iam.services.k8s.aws
        resources:
        - openidconnectproviders/status
        verbs:
        - get
        - patch
        - update
      - apiGroups:
        - iam.services.k8s.aws
        resources:
        - policies
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - iam.services.k8s.aws
        resources:
        - policies/status
        verbs:
        - get
        - patch
        - update
      - apiGroups:
        - iam.services.k8s.aws
        resources:
        - roles
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - iam.services.k8s.aws
        resources:
        - roles/status
        verbs:
        - get
        - patch
        - update
      - apiGroups:
        - iam.services.k8s.aws
        resources:
        - users
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - iam.services.k8s.aws
        resources:
        - users/status
        verbs:
        - get
        - patch
        - update
      - apiGroups:
        - services.k8s.aws
        resources:
        - adoptedresources
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - services.k8s.aws
        resources:
        - adoptedresources/status
        verbs:
        - get
        - patch
        - update
      - apiGroups:
        - services.k8s.aws
        resources:
        - fieldexports
        verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
      - apiGroups:
        - services.k8s.aws
        resources:
        - fieldexports/status
        verbs:
        - get
        - patch
        - update