apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: ekscluster.kro.run
spec:
  # CRD Schema
  schema:
    apiVersion: v1alpha1
    kind: EKSCluster
    spec:
      name: string
      version: string
    status:
      clusterARN1: ${cluster1.status.clusterARN}
      clusterARN2: ${cluster2.status.clusterARN}
  # resources
  resources:
  - id: cluster1
    template:
      apiVersion: eks.services.k8s.aws/v1alpha1
      kind: EKSCluster
      metadata:
        name: cluster1-${schema.spec.name}
      spec:
        name: cluster1-${schema.spec.name}
        version: ${spc.version}
  - id: cluster2
    template:
      apiVersion: eks.services.k8s.aws/v1alpha1
      kind: EKSCluster
      metadata:
        name: cluster2-${schema.spec.name}
      spec:
        name: cluster2-${schema.spec.name}
        version: ${spc.version}