api:
  adminAccount:
    # kargo-password
    passwordHash: $2y$10$0sA5poX4OmqqoMQEdHv4N.gHic8aM3UQeqgU0OPgzha6djiK84F5m
    tokenSigningKey: 28yCIWwbkBBBADFS62DdN4OWFqfhUvHq
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  # ingress:
  #   enabled: true
  #   ingressClassName: alb
  tls:
    enabled: false
    terminatedUpstream: true