# temporaty commentd out because we have gp3 sc in gitlab. TODO: move to earlier chart
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: gp3
#   annotations:
#     storageclass.kubernetes.io/is-default-class: "true"
# provisioner: ebs.csi.eks.amazonaws.com
# volumeBindingMode: WaitForFirstConsumer
# parameters:
#   type: gp3
#   encrypted: "true"
