apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.3/deploy/static/provider/aws/deploy.yaml
  - namespace.yaml
helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx
  namespace: ingress-nginx
  version: 4.11.1
