global:
  tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
    effect: "NoSchedule"
  domain: ${DOMAIN_NAME}
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    path: /argocd
    pathType: Prefix
  extraArgs:
    - --rootpath=/argocd
    - --basehref=/argocd
    - --insecure
  service:
    type: ClusterIP
configs:
  cm:
    url: https://${DOMAIN_NAME}/argocd
  secret:
    argocdServerAdminPassword: ${ADMIN_PASSWORD}

controller:
  env:
    - name: ARGOCD_SYNC_WAVE_DELAY
      value: '30'
